### ISSUE TITLE
Fixed Issues.

### ISSUE THREAD

**Issue by phantomD92** [appodols/interviewbasic#1]
I resolved your issues via Jinja2Templates.
![interviewbasic_debug_fix](https://github.com/appodols/interviewbasic/assets/160835524/d54e6cca-57b2-4a29-af71-a0c3ec372503)

**Comment by gladsonchala** [comment]
I have fixed your issue by changing few codes... check [PR](https://github.com/appodols/interviewbasic/pull/2) for more.

**Comment by melnixoleg** [comment]
regarding your code, you didn't resolve issue.
This project have only rendering issue.
There is no issue in analyze-text/ api.

**Comment by gladsonchala** [comment]
@melnixoleg If you're referring to mine, it's now rendering everything fine in real-time.
Sorry, If there's any misunderstanding!

**Comment by phantomD92** [comment]
This project's issue is related to template rendering.

**Comment by phantomD92** [comment]
This issues completed.

**Comment by melnixoleg** [comment]
@phantomD92 Congratulations!

**Comment by phantomD92** [comment]
Hello, @appodols.
I am waiting you now.
